default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db # Nome do contêiner na rede 'iff'
  username: postgres
  password: 1q2w3e4r
  port: 5432
  database: crud_api_db

development:
  <<: *default
  database: crud_api_db_development

test:
  <<: *default
  database: crud_api_db_test

production:
  <<: *default
  database: crud_api_db_production
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] || "db" %>  # Certifique-se de usar o nome do contêiner em produção, se for o caso.